feat(web): Add TabButton component
atnagata/reearth pull request #3
Opened 2023-05-31 07:35 UTC by atnagata

# Overview
Add TabButton component

2023-05-31 07:58 UTC, koji-endo2 requested changes

2023-05-31 07:58 UTC, koji-endo2 commented on web/src/beta/components/TabButton/index.tsx
> +  disabled: boolean;
「disabled」だとボタンを押せない状態のように受け取れます。
タブが選択されている事を示すように「selected」ではどうでしょうか。

2023-05-31 07:58 UTC, koji-endo2 commented on web/src/beta/components/TabButton/index.tsx
> +  background: ${({ disabled }) => (disabled ? "#232226" : "#232226")};
figmaでは非選択状態のタブボタンは背景色は指定されていません。

2023-06-01 04:41 UTC, atnagata commented on web/src/beta/components/TabButton/index.tsx
> +  disabled: boolean;
Fixed.

2023-06-01 04:41 UTC, atnagata commented on web/src/beta/components/TabButton/index.tsx
> +  background: ${({ disabled }) => (disabled ? "#232226" : "#232226")};
Fixed.

2023-06-02 00:17 UTC, koji-endo2 approved these changes
特に指摘はありません。

2023-06-02 02:39 UTC, merged